use_frameworks!

platform :ios, '10.0'

target 'testSwiftFramework_Example' do
  pod 'testSwiftFramework', :path => '../'

  target 'testSwiftFramework_Tests' do
    inherit! :search_paths

    
  end
end
